### ISSUE TITLE
pattern question

### ISSUE THREAD

**Issue by mr-nv** [danielkrupinski/VAC-Bypass#1]
https://github.com/danielkrupinski/VAC-Bypass/blob/master/VAC-Bypass/dllmain.c#L7-L12
ive seen you do the same thing in your vac-hooks repo, and im interested in what does this pattern lead to and why you patch it
please answer, thanks

**Comment by danielkrupinski** [comment]
Without this patch VAC modules are loaded from memory without being stored on disk. Patch forces steamservice.dll to load modules using LoadLibraryExW function which we hook and apply more hooks there.

**Comment by Speedi13** [comment]
why don't you just hook the manual mapper?
You can easily detour all Imports by hooking GetProcAddress (because the manual mapper resolves them all with it)

**Comment by danielkrupinski** [comment]
@Speedi13 Either way is good.

**Comment by mr-nv** [comment]
@danielkrupinski got it, thanks for answering
