### ISSUE TITLE
How does it works?

### ISSUE THREAD

**Issue by hyperxpro** [danielkrupinski/VAC-Bypass#10]
Just wanted to know does it work. 

> We inject VAC-Bypass.dll into Steam.exe process.
> Start CS:GO
> Inject CS:GO Cheat like Osiris.

That's it? VAC-Bypass will take care of rest? No need of cheat modification?

**Comment by danielkrupinski** [comment]
Yes, don't forget to disconnect from the internet when injecting bypass manually or use automatic [loader](https://github.com/danielkrupinski/VAC-Bypass-Loader)
