### ISSUE TITLE
Cant get in to steam account while using Vac-Bypass

### ISSUE THREAD

**Issue by syfexx** [danielkrupinski/VAC-Bypass#11]
Its just says like this:
(https://user-images.githubusercontent.com/17620391/68708201-851fb300-0593-11ea-8451-b60d65a49fba.PNG)

**Comment by Alluseri** [comment]
Same for me.

**Comment by danielkrupinski** [comment]
Use [bypass loader](https://github.com/danielkrupinski/VAC-Bypass-Loader).
