### ISSUE TITLE
Doubts Bypass

### ISSUE THREAD

**Issue by Leleo-code** [danielkrupinski/VAC-Bypass#19]
Hello Daniel

I have some doubts about VAC bypass

- Do I have to inject it again whenever I close the steam or restart the pc?

- When this Vac Bypass is detecting (I don't know if this will happen), will you let me know here on Github?

Thank you for making this brilliant Bypass available! I'm certainly very grateful! ^^

**Comment by rafalohaki** [comment]
1. U need inject it again if u click change user/log out/start steam.exe again.
2.Im pretty sure he will archive this repo or edit readme and before it happen, we will see information in issue section and that's how we will know. I dont think he has time to check it with interval like 1 time a hour, more like 1 time day or 2 days, maybe he doesn't check at all and there is community for it which use it and check it. that's only mine opinion in this point and sry for my eng.
