### ISSUE TITLE
NOT AN ISSUE BUT A QUESTION!

### ISSUE THREAD

**Issue by January-0002** [danielkrupinski/VAC-Bypass#20]
I'm VERY new to hacking and I'm a bit confused as to what this does exactly. Does it:

1) Bypass VAC so you don't get banned WHILE you're hacking
2) Bypass VAC so your ALREADY BANNED account can get on?

Your help is appreciated, will close immediately after :)

**Comment by danielkrupinski** [comment]
First option.
