### ISSUE TITLE
is it completely safe?

### ISSUE THREAD

**Issue by 2deus** [danielkrupinski/VAC-Bypass#23]
you know, things like these are very rare and just sound ambitious. Can I get Untrusted by this? I alr tested VAC, it worked perfectly fine.

**Comment by danielkrupinski** [comment]
Untrusted ban from sending invalid view angles to the server - yes, you can.

**Comment by 2deus** [comment]
Can this be easily patched? and are valve alr working on it? cheers

**Comment by danielkrupinski** [comment]
> Can this be easily patched?

Yep

> and are valve alr working on it?

idk

I would use it only to not get instantly banned with cheats / programs that are known to be detected.
