### ISSUE TITLE
FIXED

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/VAC-Bypass#25]
The bypass got fixed at around 10:00 PM (GMT+1) 3/20/2020

REST IN PEACE

**Comment by danielkrupinski** [comment]
How did you come to this conclusion?

**Comment by ghost** [comment]
When I and my friend have the bypass on Steam says it can't connect or something like that.

**Comment by ghost** [comment]
Wait what
it works again

**Comment by ghost** [comment]
i checked it and everything

**Comment by ghost** [comment]
can i ask, where are you from?

**Comment by danielkrupinski** [comment]
Poland

**Comment by ghost** [comment]
mozemy kontynuowac przez email?
