### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JustKraskata** [danielkrupinski/VAC-Bypass#26]
Is it up-to-date and can I use it with game like CS 1.6? Can I get VAC for using this buypass and can I get VAC if I use detected cheat with this bypass?

**Comment by danielkrupinski** [comment]
CS 1.6 uses older version of VAC. This bypass should work for all Source engine games, but it's been tested with CS:GO only. Its purpose is to avoid bans while using detected cheats or blacklisted programs (e.g Cheat Engine).
