### ISSUE TITLE
The question

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/VAC-Bypass#27]
Hello Daniel,

I wanna to ask you, it is okay to use VAC-Bypass still? I wanna to try on my prime account.

And do you suggest using VAC-Bypass with Osiris?

And yeah, what are chance to get bannes using this(kinda stupid)?

+ I appriciate that work you put on Osiris,ESP,VAC-Bypass and other things.
+ Thanks.

**Comment by orzobinbo** [comment]
Dunno if it is patched, but don't be such a retardo and use anything on your main bruv. Better safe than sorry 💃

**Comment by danielkrupinski** [comment]
It still works but remember you're the only responsible for your actions.
