### ISSUE TITLE
Detection question

### ISSUE THREAD

**Issue by Shaxzy** [danielkrupinski/VAC-Bypass#3]
Wouldn't valve be able to detect this as a normal .dll cheat? 
They could just manually add this to their VAC system.

I'm just asking since I see this has gotten some attention.
https://youtu.be/3KK83SbCSd8

**Comment by danielkrupinski** [comment]
How would they detect this if it disables VAC entirely? Also VAC does not scan steam process.

**Comment by Shaxzy** [comment]
Ah allright, gucci
