### ISSUE TITLE
Add a Menu.

### ISSUE THREAD

**Issue by techzin** [danielkrupinski/VAC-Bypass#31]
Hey, add a menu to Question, Apply Bypass? Yes or No.

**Comment by rafalohaki** [comment]
u apply by launching it. what sense to launch exe and then have button to launch

**Comment by PekSec** [comment]
why would you need a no button?

**Comment by techzin** [comment]
> por que você precisaria de um botão não?

everyone around me asked the same question, and I didn't know what to say lol
