### ISSUE TITLE
Convert DLL to Bytes

### ISSUE THREAD

**Issue by techzin** [danielkrupinski/VAC-Bypass#32]
How can I convert the dll into bytes to use in VAC Bypass Loader?

**Comment by techzin** [comment]
I have found -> https://tomeko.net/online_tools/file_to_hex.php?lang=en
Convert DLL generated By [Vac Bypass](https://github.com/danielkrupinski/VAC-Bypass)
And Insert to binary.h in [VAC Bypass Loader](https://github.com/danielkrupinski/VAC-Bypass-Loader)

**Comment by altro50** [comment]
Just drag it into a hex editor like HXD, replace spaces with `, 0x` and prefix it with 0x.

**Comment by jwao** [comment]
Does this even works anymore?

**Comment by techzin** [comment]
Working!!

> Does this even works anymore?

Working...
