### ISSUE TITLE
Is VAC Bypass still works?

### ISSUE THREAD

**Issue by Meff1u** [danielkrupinski/VAC-Bypass#35]
I got VAC BAN using VAC Bypass Loader ;/

**Comment by rafalohaki** [comment]
spam /close

**Comment by Meff1u** [comment]
lol

**Comment by Meff1u** [comment]
I really want to know if bypass works

**Comment by SleekZ** [comment]
Pretty sure it does, I've been raging with OTC for 2 days straight - no ban.

**Comment by MasterChief220** [comment]
does it still work after the new van anti cheat?

**Comment by rafalohaki** [comment]
it still works... /close

**Comment by ghost** [comment]
Close this
