### ISSUE TITLE
Steam won't complete login process

### ISSUE THREAD

**Issue by Bluetinity** [danielkrupinski/VAC-Bypass#43]
After doing the injection process steam will say Connecting Steam account but won't finish. Any suggestions?

**Comment by Bluetinity** [comment]
Did everything as instructed, but am using an injector (https://github.com/mdilai/Shtreeba)

**Comment by hugohabicht01** [comment]
Same for me, using ExtremeInjector, it just loads infinitely.

**Comment by rafalohaki** [comment]
use vac bypass loader

**Comment by hugohabicht01** [comment]
I already tried that, doesn't work either.

**Comment by ghost** [comment]
Close this, it works with the loader.

**Comment by hugohabicht01** [comment]
I personally fixed it by just recompiling, idk why that worked, but it did

**Comment by ghost** [comment]
Probably didnt pull the latest changes, or your file got corrupted.
