### ISSUE TITLE
VAC was unable to verify your game session, please help ASAP

### ISSUE THREAD

**Issue by KaramBotStudios-DEV1** [danielkrupinski/VAC-Bypass#45]
every 30 minutes it says vac was unable to verufy your game session

**Comment by BotAndis** [comment]
Veryify Ur game session I can do this in Steam and csgo propertys (veryify gamedata or something like that) also logout and wait 10 min and login again... If doesn't work restart pc  after verify of game data

**Comment by KaramBotStudios-DEV1** [comment]
> Veryify Ur game session I can do this in Steam and csgo propertys (veryify gamedata or something like that) also logout and wait 10 min and login again... If doesn't work restart pc after verify of game data

Nope it doesn't work

**Comment by BotAndis** [comment]
Strange

**Comment by ghost** [comment]
uninstall/reinstall csgo, close this issue
