### ISSUE TITLE
Stuck in Connecting Steam Account

### ISSUE THREAD

**Issue by sestain** [danielkrupinski/VAC-Bypass#5]
When I inject vac bypass dll to steam without internet and turn on internet and click retry its just stuck saying Connecting Steam Account: (account name)...
What am I doing wrong?

**Comment by danielkrupinski** [comment]
It's Steam bug. Some people say that launching Steam in Big Picture mode fixes this issue.

**Comment by danielkrupinski** [comment]
Now you can use [VAC Bypass Loader](https://github.com/danielkrupinski/VAC-Bypass-Loader) which does not require disconnecting from the internet.
