### ISSUE TITLE
I get these errors when I try to compile

### ISSUE THREAD

**Issue by DragonSeason** [danielkrupinski/VAC-Bypass#50]
Hello there
I get the same error in 3 different files.
dllmain.c     line 24
Hooks.c       line 95
Utils.c          line 61
"Unexpected file ending while searching for pre compiled Header. You might have forgotten to add "#include "pch.h"" to the source code."

Hope you can help me.

**Comment by Our-ly** [comment]
add "#include "pch.h" to the files it says.. lmao

**Comment by Ciccon0** [comment]
I have the same problem and I can't figure out how to fix it
