### ISSUE TITLE
VAC-Ban bypass dosn't work.

### ISSUE THREAD

**Issue by k0ssa** [danielkrupinski/VAC-Bypass#56]
I tried to lost of compilations of injecting (according to the instructions) and from other forums. Dosn't work at all. Its injecting to the steam but my vac is still here. I got a ,,injection completed" message.

**Comment by bacontsu** [comment]
its not a vac remover

**Comment by k0ssa** [comment]
> its not a vac remover

damn, im dumb i think this can bypass vac'ed account xD
