### ISSUE TITLE
Doesnt work or am I dumb?

### ISSUE THREAD

**Issue by hellxsuicide** [danielkrupinski/VAC-Bypass#6]
So I followed the exact steps, but I still have a "Permanent Ban" in CSGO menu and cant start a game? Am I doing it right or am I just being stoopid?

**Comment by danielkrupinski** [comment]
It doesn't remove VAC bans.

**Comment by hellxsuicide** [comment]
what does it do then?

**Comment by danielkrupinski** [comment]
It blocks VAC from detecting cheats.

**Comment by hellxsuicide** [comment]
Just got that, sry

**Comment by SimpleRealistic** [comment]
It removed my vac ban

I don’t know what your issue is

I’ve been buying banned steam accounts with knives on them for super cheap, and selling them after I unban them.

**Comment by hellxsuicide** [comment]
Really duud? Dint work for me??

SimpleRealistic <notifications@github.com> schrieb am Mo., 30. Sep. 2019,
06:06:

**Comment by appleman1232** [comment]
autism

**Comment by cptmacp** [comment]
@SimpleRealistic

i see what you did there .
