### ISSUE TITLE
 unexpected end of file while looking for precompiled header how to fix?

### ISSUE THREAD

**Issue by pogixepa** [danielkrupinski/VAC-Bypass#7]
i get " unexpected end of file while looking for precompiled header." how do i fix this

**Comment by gisohh** [comment]
I'm getting this error aswell, is this patched?

**Comment by 3y2189ewq** [comment]
same

**Comment by danielkrupinski** [comment]
Compile in x86 release mode.

**Comment by pogixepa** [comment]
> Compile in x86 release mode.

thank you!
