### ISSUE TITLE
[PATCHED] VAC is unable to communicate error

### ISSUE THREAD

**Issue by free0ne87** [danielkrupinski/VAC-Bypass#80]
As title..
VAC-Bypass + Osiris
Disconnected on 3rd round, keeps disconnecting on retry..
Keeps disconnecting on restart + retry + no inject..
Used [start C:\Program Files (x86)\Steam\bin\SteamService.exe /repair] + restart
Reconnected successfully with no inject..
Match end followed by 20 mins cooldown
WIN11, Build x86, SDK 10.0.22621.0, platform v143, Microsoft Visual Studio 2022 v17.2.4, Latest repositories SRC

https://help.steampowered.com/en/faqs/view/22C0-03D0-AE4B-04E8

**Comment by fanat1cc** [comment]
verify game files and play a round without vac bypass/ cheats in (casual) exit csgo and launch vac bypass then inject
