### ISSUE TITLE
Hooks manipulating Functions to disable VAC?

### ISSUE THREAD

**Issue by 0xE232FE** [danielkrupinski/VAC-Bypass#9]
You modify the Functions **GetProcAddress**, **GetSystemInfo** with this Hook?

So **FARPROC** is a function pointer.

`return (FARPROC)Hooks_GetSystemInfo`
So VAC gets a null pointer?

**Comment by danielkrupinski** [comment]
See https://github.com/danielkrupinski/VAC-Bypass/blob/master/README.md#how-it-works

**Comment by 0xE232FE** [comment]
appreciate thank you!!!
